name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry run pip install --upgrade pip
      - name: Lint with flake8
        run: |
          poetry run flake8 .
      - name: Type checking with MyPy
        run: |
          poetry run mypy --strict
      - name: Test with pytest
        run: |
          poetry run pytest --cov-report term-missing --cov={{ cookiecutter.project_name | slugify(separator='_') }}
          poetry run coverage xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unit
